server.port=8080

# Conexión dinámica con las variables de Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de base de datos para que sea permanente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuraciones de archivos y codificación
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB
spring.thymeleaf.encoding=UTF-8
